apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres.:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: "disable"
      database: test